# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-24 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectviewed',
            name='comment',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
