# Generated by Django 2.0.5 on 2018-05-25 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0007_auto_20180523_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='billing_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billings.BillingProfile'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='billing_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billings.BillingProfile'),
        ),
    ]
